---
kind: pipeline
type: docker
name: deploy

steps:
  - name: staging
    image: alpine
    commands:
      - echo "staging"

  - name: production
    image: alpine
    commands:
      - echo "production"
    when:
      event:
      - promote
      target:
      - production
